version: '3.9'

services:
  app:
    build:
      target: dev
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  postgres:
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@test.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "5050:80"
    logging:
      driver: "json-file"
      options:
        max-size: "99M"
        max-file: "1"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
