# Generated by Django 3.2 on 2022-04-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_orderproduct_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='price',
            new_name='cost',
        ),
    ]
