# Generated by Django 3.2 on 2022-04-23 10:24

from django.db import migrations
from django.db.models import Q, F


def calculate_cost(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')
    OrderProduct.objects.filter(Q(cost__isnull=True) | Q(cost=0)).update(cost=F('product__price') * F('quantity'))


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_rename_price_orderproduct_cost'),
    ]

    operations = [
        migrations.RunPython(calculate_cost),
    ]
