# Generated by Django 3.2 on 2022-04-23 10:24

from django.db import migrations
from django.db.models import Q, F, OuterRef, Subquery


def calculate_cost(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')

    # Method 1. Илья, так ведь можно?
    # Если делать так:
    # OrderProduct.objects.filter(Q(cost__isnull=True) | Q(cost=0)).update(cost=F('product__price') * F('quantity'))
    # то выходит ошибка:
    # "FieldError: Joined field references are not permitted in this query"
    # С F() нельзя добраться до product__price (до связанной таблицы).
    # Вот способ:
    # OrderProduct.objects.filter(Q(cost__isnull=True) | Q(cost=0)).update(
    #     cost=Subquery(OrderProduct.objects.filter(pk=OuterRef('pk')).values('product__price')) * F('quantity'))

    # Method 2
    for order_product in OrderProduct.objects.filter(Q(cost__isnull=True) | Q(cost=0)).iterator(chunk_size=1000):
        order_product.cost = order_product.product.price * order_product.quantity
        order_product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_rename_price_orderproduct_cost'),
    ]

    operations = [
        migrations.RunPython(calculate_cost),
    ]
