# Generated by Django 3.2 on 2022-05-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Необработанный'), ('CLOSED', 'Закрыт')], db_index=True, default='NEW', max_length=6, verbose_name='Статус'),
        ),
    ]
