# Generated by Django 3.2 on 2022-05-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20220506_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='called_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата и время звонка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата и время доставки'),
        ),
    ]
