# Generated by Django 3.2 on 2022-05-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_auto_20220506_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('NOTSET', 'Не установлено'), ('CASH', 'Наличными'), ('ELECTRONIC', 'Элетронно')], db_index=True, default='NOTSET', max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
