# Generated by Django 3.2 on 2022-05-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geoaddress',
            options={'verbose_name': 'Координаты адресов', 'verbose_name_plural': 'Координаты адресов'},
        ),
    ]
