# Generated by Django 3.2 on 2022-05-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_address', '0002_alter_geoaddress_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoaddress',
            old_name='lng',
            new_name='lon',
        ),
    ]
