# Generated by Django 3.2 on 2022-05-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_address', '0003_rename_lng_geoaddress_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoaddress',
            name='lon',
            field=models.DecimalField(decimal_places=15, help_text='longitude, lon', max_digits=17, verbose_name='Координаты: долгота'),
        ),
    ]
