# Generated by Django 3.2 on 2022-07-02 15:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('geo_address', '0004_alter_geoaddress_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoaddress',
            name='update_date',
            field=models.DateField(auto_now=True, db_index=True, default=datetime.datetime(2022, 7, 2, 15, 20, 37, 182492, tzinfo=utc), verbose_name='Дата обновления координат'),
            preserve_default=False,
        ),
    ]
